// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v7.34.1
// source: agent.proto

package agentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskState int32

const (
	TaskState_TASK_STATE_UNSPECIFIED TaskState = 0
	TaskState_TASK_STATE_PENDING     TaskState = 1
	TaskState_TASK_STATE_RUNNING     TaskState = 2
	TaskState_TASK_STATE_SUCCEEDED   TaskState = 3
	TaskState_TASK_STATE_FAILED      TaskState = 4
	TaskState_TASK_STATE_CANCELLED   TaskState = 5
)

// Enum value maps for TaskState.
var (
	TaskState_name = map[int32]string{
		0: "TASK_STATE_UNSPECIFIED",
		1: "TASK_STATE_PENDING",
		2: "TASK_STATE_RUNNING",
		3: "TASK_STATE_SUCCEEDED",
		4: "TASK_STATE_FAILED",
		5: "TASK_STATE_CANCELLED",
	}
	TaskState_value = map[string]int32{
		"TASK_STATE_UNSPECIFIED": 0,
		"TASK_STATE_PENDING":     1,
		"TASK_STATE_RUNNING":     2,
		"TASK_STATE_SUCCEEDED":   3,
		"TASK_STATE_FAILED":      4,
		"TASK_STATE_CANCELLED":   5,
	}
)

func (x TaskState) Enum() *TaskState {
	p := new(TaskState)
	*p = x
	return p
}

func (x TaskState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskState) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_proto_enumTypes[0].Descriptor()
}

func (TaskState) Type() protoreflect.EnumType {
	return &file_agent_proto_enumTypes[0]
}

func (x TaskState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskState.Descriptor instead.
func (TaskState) EnumDescriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

type LogLine_Stream int32

const (
	LogLine_STREAM_UNSPECIFIED LogLine_Stream = 0
	LogLine_STREAM_STDOUT      LogLine_Stream = 1
	LogLine_STREAM_STDERR      LogLine_Stream = 2
)

// Enum value maps for LogLine_Stream.
var (
	LogLine_Stream_name = map[int32]string{
		0: "STREAM_UNSPECIFIED",
		1: "STREAM_STDOUT",
		2: "STREAM_STDERR",
	}
	LogLine_Stream_value = map[string]int32{
		"STREAM_UNSPECIFIED": 0,
		"STREAM_STDOUT":      1,
		"STREAM_STDERR":      2,
	}
)

func (x LogLine_Stream) Enum() *LogLine_Stream {
	p := new(LogLine_Stream)
	*p = x
	return p
}

func (x LogLine_Stream) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogLine_Stream) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_proto_enumTypes[1].Descriptor()
}

func (LogLine_Stream) Type() protoreflect.EnumType {
	return &file_agent_proto_enumTypes[1]
}

func (x LogLine_Stream) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogLine_Stream.Descriptor instead.
func (LogLine_Stream) EnumDescriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{7, 0}
}

type DispatchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Opaque, server-assigned identifier for the task.
	TaskId string `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	// Command to execute, including any arguments.
	Argv []string `protobuf:"bytes,2,rep,name=argv,proto3" json:"argv,omitempty"`
	// Environment variables to set for the task ("KEY=VALUE").
	Env           []string `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatchRequest) Reset() {
	*x = DispatchRequest{}
	mi := &file_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchRequest) ProtoMessage() {}

func (x *DispatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchRequest.ProtoReflect.Descriptor instead.
func (*DispatchRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

func (x *DispatchRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *DispatchRequest) GetArgv() []string {
	if x != nil {
		return x.Argv
	}
	return nil
}

func (x *DispatchRequest) GetEnv() []string {
	if x != nil {
		return x.Env
	}
	return nil
}

type DispatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	State         TaskState              `protobuf:"varint,2,opt,name=state,proto3,enum=cmnweave.agent.v1.TaskState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatchResponse) Reset() {
	*x = DispatchResponse{}
	mi := &file_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchResponse) ProtoMessage() {}

func (x *DispatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchResponse.ProtoReflect.Descriptor instead.
func (*DispatchResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

func (x *DispatchResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *DispatchResponse) GetState() TaskState {
	if x != nil {
		return x.State
	}
	return TaskState_TASK_STATE_UNSPECIFIED
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

func (x *StatusRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	State         TaskState              `protobuf:"varint,2,opt,name=state,proto3,enum=cmnweave.agent.v1.TaskState" json:"state,omitempty"`
	ExitCode      int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{3}
}

func (x *StatusResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *StatusResponse) GetState() TaskState {
	if x != nil {
		return x.State
	}
	return TaskState_TASK_STATE_UNSPECIFIED
}

func (x *StatusResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *StatusResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type CancelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRequest) Reset() {
	*x = CancelRequest{}
	mi := &file_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequest) ProtoMessage() {}

func (x *CancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequest.ProtoReflect.Descriptor instead.
func (*CancelRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{4}
}

func (x *CancelRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type CancelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	State         TaskState              `protobuf:"varint,2,opt,name=state,proto3,enum=cmnweave.agent.v1.TaskState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelResponse) Reset() {
	*x = CancelResponse{}
	mi := &file_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelResponse) ProtoMessage() {}

func (x *CancelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelResponse.ProtoReflect.Descriptor instead.
func (*CancelResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{5}
}

func (x *CancelResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *CancelResponse) GetState() TaskState {
	if x != nil {
		return x.State
	}
	return TaskState_TASK_STATE_UNSPECIFIED
}

type StreamLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamLogsRequest) Reset() {
	*x = StreamLogsRequest{}
	mi := &file_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamLogsRequest) ProtoMessage() {}

func (x *StreamLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamLogsRequest.ProtoReflect.Descriptor instead.
func (*StreamLogsRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{6}
}

func (x *StreamLogsRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type LogLine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Stream        LogLine_Stream         `protobuf:"varint,2,opt,name=stream,proto3,enum=cmnweave.agent.v1.LogLine_Stream" json:"stream,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogLine) Reset() {
	*x = LogLine{}
	mi := &file_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogLine) ProtoMessage() {}

func (x *LogLine) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogLine.ProtoReflect.Descriptor instead.
func (*LogLine) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{7}
}

func (x *LogLine) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *LogLine) GetStream() LogLine_Stream {
	if x != nil {
		return x.Stream
	}
	return LogLine_STREAM_UNSPECIFIED
}

func (x *LogLine) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_agent_proto protoreflect.FileDescriptor

const file_agent_proto_rawDesc = "" +
	"\n" +
	"\vagent.proto\x12\x11cmnweave.agent.v1\"P\n" +
	"\x0fDispatchRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x12\n" +
	"\x04argv\x18\x02 \x03(\tR\x04argv\x12\x10\n" +
	"\x03env\x18\x03 \x03(\tR\x03env\"_\n" +
	"\x10DispatchResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x122\n" +
	"\x05state\x18\x02 \x01(\x0e2\x1c.cmnweave.agent.v1.TaskStateR\x05state\"(\n" +
	"\rStatusRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"\x9f\x01\n" +
	"\x0eStatusResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x122\n" +
	"\x05state\x18\x02 \x01(\x0e2\x1c.cmnweave.agent.v1.TaskStateR\x05state\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"(\n" +
	"\rCancelRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"]\n" +
	"\x0eCancelResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x122\n" +
	"\x05state\x18\x02 \x01(\x0e2\x1c.cmnweave.agent.v1.TaskStateR\x05state\",\n" +
	"\x11StreamLogsRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"\xb9\x01\n" +
	"\aLogLine\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x129\n" +
	"\x06stream\x18\x02 \x01(\x0e2!.cmnweave.agent.v1.LogLine.StreamR\x06stream\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"F\n" +
	"\x06Stream\x12\x16\n" +
	"\x12STREAM_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSTREAM_STDOUT\x10\x01\x12\x11\n" +
	"\rSTREAM_STDERR\x10\x02*\xa2\x01\n" +
	"\tTaskState\x12\x1a\n" +
	"\x16TASK_STATE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12TASK_STATE_PENDING\x10\x01\x12\x16\n" +
	"\x12TASK_STATE_RUNNING\x10\x02\x12\x18\n" +
	"\x14TASK_STATE_SUCCEEDED\x10\x03\x12\x15\n" +
	"\x11TASK_STATE_FAILED\x10\x04\x12\x18\n" +
	"\x14TASK_STATE_CANCELLED\x10\x052\xd3\x02\n" +
	"\fAgentService\x12S\n" +
	"\bDispatch\x12\".cmnweave.agent.v1.DispatchRequest\x1a#.cmnweave.agent.v1.DispatchResponse\x12M\n" +
	"\x06Status\x12 .cmnweave.agent.v1.StatusRequest\x1a!.cmnweave.agent.v1.StatusResponse\x12M\n" +
	"\x06Cancel\x12 .cmnweave.agent.v1.CancelRequest\x1a!.cmnweave.agent.v1.CancelResponse\x12P\n" +
	"\n" +
	"StreamLogs\x12$.cmnweave.agent.v1.StreamLogsRequest\x1a\x1a.cmnweave.agent.v1.LogLine0\x01B<Z:github.com/ryo-arima/cmn-weave/pkg/agent/grpc/auto;agentpbb\x06proto3"

var (
	file_agent_proto_rawDescOnce sync.Once
	file_agent_proto_rawDescData []byte
)

func file_agent_proto_rawDescGZIP() []byte {
	file_agent_proto_rawDescOnce.Do(func() {
		file_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)))
	})
	return file_agent_proto_rawDescData
}

var file_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_agent_proto_goTypes = []any{
	(TaskState)(0),            // 0: cmnweave.agent.v1.TaskState
	(LogLine_Stream)(0),       // 1: cmnweave.agent.v1.LogLine.Stream
	(*DispatchRequest)(nil),   // 2: cmnweave.agent.v1.DispatchRequest
	(*DispatchResponse)(nil),  // 3: cmnweave.agent.v1.DispatchResponse
	(*StatusRequest)(nil),     // 4: cmnweave.agent.v1.StatusRequest
	(*StatusResponse)(nil),    // 5: cmnweave.agent.v1.StatusResponse
	(*CancelRequest)(nil),     // 6: cmnweave.agent.v1.CancelRequest
	(*CancelResponse)(nil),    // 7: cmnweave.agent.v1.CancelResponse
	(*StreamLogsRequest)(nil), // 8: cmnweave.agent.v1.StreamLogsRequest
	(*LogLine)(nil),           // 9: cmnweave.agent.v1.LogLine
}
var file_agent_proto_depIdxs = []int32{
	0, // 0: cmnweave.agent.v1.DispatchResponse.state:type_name -> cmnweave.agent.v1.TaskState
	0, // 1: cmnweave.agent.v1.StatusResponse.state:type_name -> cmnweave.agent.v1.TaskState
	0, // 2: cmnweave.agent.v1.CancelResponse.state:type_name -> cmnweave.agent.v1.TaskState
	1, // 3: cmnweave.agent.v1.LogLine.stream:type_name -> cmnweave.agent.v1.LogLine.Stream
	2, // 4: cmnweave.agent.v1.AgentService.Dispatch:input_type -> cmnweave.agent.v1.DispatchRequest
	4, // 5: cmnweave.agent.v1.AgentService.Status:input_type -> cmnweave.agent.v1.StatusRequest
	6, // 6: cmnweave.agent.v1.AgentService.Cancel:input_type -> cmnweave.agent.v1.CancelRequest
	8, // 7: cmnweave.agent.v1.AgentService.StreamLogs:input_type -> cmnweave.agent.v1.StreamLogsRequest
	3, // 8: cmnweave.agent.v1.AgentService.Dispatch:output_type -> cmnweave.agent.v1.DispatchResponse
	5, // 9: cmnweave.agent.v1.AgentService.Status:output_type -> cmnweave.agent.v1.StatusResponse
	7, // 10: cmnweave.agent.v1.AgentService.Cancel:output_type -> cmnweave.agent.v1.CancelResponse
	9, // 11: cmnweave.agent.v1.AgentService.StreamLogs:output_type -> cmnweave.agent.v1.LogLine
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_agent_proto_init() }
func file_agent_proto_init() {
	if File_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_depIdxs,
		EnumInfos:         file_agent_proto_enumTypes,
		MessageInfos:      file_agent_proto_msgTypes,
	}.Build()
	File_agent_proto = out.File
	file_agent_proto_goTypes = nil
	file_agent_proto_depIdxs = nil
}
