#ifndef CMNWEAVE_CORE_H
#define CMNWEAVE_CORE_H

#pragma once

/* Generated by cbindgen. Do not edit by hand. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Maximum length (bytes) for path / string fields in proc structs.
 */
#define CMNWEAVE_BUF_LEN 4096

/**
 * Maximum number of argv / env entries captured.
 */
#define CMNWEAVE_ARGV_MAX 256

/**
 * Subset of fields from `/proc/<pid>/status` that the agent reports back to
 * the server.
 *
 * Unread / unparseable fields are left at their zero values.
 */
typedef struct CmnweaveProcStatus {
  /**
   * Process name (Name: field), NUL-terminated.
   */
  uint8_t name[64];
  /**
   * Single-character state (State: field): 'R','S','D','Z','T','t','I'.
   */
  uint8_t state;
  /**
   * Process ID.
   */
  int32_t pid;
  /**
   * Parent process ID.
   */
  int32_t ppid;
  /**
   * Number of threads (Threads: field).
   */
  int32_t threads;
  /**
   * Virtual memory peak in kB (VmPeak:).
   */
  int64_t vm_peak_kb;
  /**
   * Resident set size in kB (VmRSS:).
   */
  int64_t vm_rss_kb;
  /**
   * Voluntary context switches (voluntary_ctxt_switches:).
   */
  int64_t voluntary_ctxt_switches;
  /**
   * Non-voluntary context switches (nonvoluntary_ctxt_switches:).
   */
  int64_t nonvoluntary_ctxt_switches;
} CmnweaveProcStatus;

/**
 * Key fields from `/proc/<pid>/stat` (space-separated).
 *
 * Only the fields needed for task reporting are captured.
 */
typedef struct CmnweaveProcStat {
  int32_t pid;
  /**
   * Process state character (field 3).
   */
  uint8_t state;
  int32_t ppid;
  /**
   * User-mode CPU time in clock ticks (field 14, utime).
   */
  int64_t utime;
  /**
   * Kernel-mode CPU time in clock ticks (field 15, stime).
   */
  int64_t stime;
  /**
   * Start time in clock ticks since boot (field 22, starttime).
   */
  int64_t starttime;
  /**
   * Virtual memory size in bytes (field 23, vsize).
   */
  int64_t vsize;
  /**
   * RSS in pages (field 24, rss).
   */
  int64_t rss_pages;
  /**
   * Exit signal number (field 38).
   */
  int32_t exit_signal;
} CmnweaveProcStat;

/**
 * NUL-separated command line from `/proc/<pid>/cmdline`.
 *
 * `argc` holds the number of entries written into `argv`; each entry is a
 * NUL-terminated C string stored in the fixed inline buffer `buf`.  The
 * `argv` array contains byte-offsets from `buf[0]` to each argument start.
 */
typedef struct CmnweaveProcCmdline {
  /**
   * Flat byte buffer holding all argv strings, NUL-terminated and packed.
   */
  uint8_t buf[CMNWEAVE_BUF_LEN];
  /**
   * Byte offsets into `buf` for each argument; `argc` entries are valid.
   */
  uint32_t offsets[CMNWEAVE_ARGV_MAX];
  /**
   * Number of valid entries in `offsets`.
   */
  uint32_t argc;
} CmnweaveProcCmdline;

/**
 * NUL-separated environment from `/proc/<pid>/environ`.
 * Layout is identical to `CmnweaveProcCmdline`.
 */
typedef struct CmnweaveProcEnviron {
  uint8_t buf[CMNWEAVE_BUF_LEN];
  uint32_t offsets[CMNWEAVE_ARGV_MAX];
  uint32_t envc;
} CmnweaveProcEnviron;

/**
 * Resolved path of the executable from `/proc/<pid>/exe`.
 */
typedef struct CmnweaveProcExe {
  /**
   * NUL-terminated absolute path. Truncated to `CMNWEAVE_BUF_LEN - 1` bytes
   * if the path exceeds the buffer.
   */
  uint8_t path[CMNWEAVE_BUF_LEN];
  /**
   * Actual byte length of `path` (excluding NUL terminator).
   */
  uint32_t len;
} CmnweaveProcExe;

/**
 * Aggregate of all live process information for a single PID.
 *
 * Each sub-struct can also be read individually via the dedicated functions
 * above; this composite type allows Go to make a single FFI call.
 */
typedef struct CmnweaveProcInfo {
  struct CmnweaveProcStatus status;
  struct CmnweaveProcStat stat;
  struct CmnweaveProcCmdline cmdline;
  struct CmnweaveProcEnviron environ;
  struct CmnweaveProcExe exe;
} CmnweaveProcInfo;

/**
 * Returns the semantic version of the core library encoded as a packed
 * `u32`: `(major << 16) | (minor << 8) | patch`.
 */
uint32_t cmnweave_core_version(void);

/**
 * Reads `/proc/<pid>/status` and writes the parsed fields into `*out`.
 *
 * Returns 0 on success, -1 if the file cannot be read, -2 on parse errors.
 * On any non-zero return the contents of `*out` are undefined.
 *
 * # Safety
 * `out` must be a valid, aligned, non-null pointer to a `CmnweaveProcStatus`.
 */
int32_t cmnweave_read_proc_status(int32_t pid, struct CmnweaveProcStatus *out);

/**
 * Reads `/proc/<pid>/stat` and writes parsed fields into `*out`.
 *
 * Returns 0 on success, -1 on read error, -2 on parse error.
 *
 * # Safety
 * `out` must be a valid, aligned, non-null pointer to a `CmnweaveProcStat`.
 */
int32_t cmnweave_read_proc_stat(int32_t pid, struct CmnweaveProcStat *out);

/**
 * Reads `/proc/<pid>/cmdline` and writes parsed data into `*out`.
 *
 * Returns 0 on success, -1 on read error.
 *
 * # Safety
 * `out` must be a valid, aligned, non-null pointer to a `CmnweaveProcCmdline`.
 */
int32_t cmnweave_read_proc_cmdline(int32_t pid, struct CmnweaveProcCmdline *out);

/**
 * Reads `/proc/<pid>/environ` and writes parsed data into `*out`.
 *
 * Returns 0 on success, -1 on read error.
 *
 * # Safety
 * `out` must be a valid, aligned, non-null pointer to a `CmnweaveProcEnviron`.
 */
int32_t cmnweave_read_proc_environ(int32_t pid, struct CmnweaveProcEnviron *out);

/**
 * Resolves `/proc/<pid>/exe` and writes the path into `*out`.
 *
 * Returns 0 on success, -1 on error.
 *
 * # Safety
 * `out` must be a valid, aligned, non-null pointer to a `CmnweaveProcExe`.
 */
int32_t cmnweave_read_proc_exe(int32_t pid, struct CmnweaveProcExe *out);

/**
 * Reads all `/proc/<pid>/*` sources into `*out` with a single call.
 *
 * `status` and `stat` are mandatory: if either fails the function returns
 * their error code immediately and `*out` is in an undefined state.
 * `cmdline`, `environ`, and `exe` are best-effort: failures are silently
 * ignored and the corresponding sub-structs are left zeroed.
 *
 * Returns 0 on success, or the non-zero rc from the first mandatory failure.
 *
 * # Safety
 * `out` must be a valid, aligned, non-null pointer to a `CmnweaveProcInfo`.
 */
int32_t cmnweave_read_proc_info(int32_t pid, struct CmnweaveProcInfo *out);

#endif  /* CMNWEAVE_CORE_H */
