use std::env;
use std::path::PathBuf;

fn main() {
    let crate_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let out_dir: PathBuf = env::var("OUT_DIR").expect("OUT_DIR").into();

    let builder = cbindgen::Builder::new()
        .with_crate(&crate_dir)
        .with_language(cbindgen::Language::C)
        .with_include_guard("CMNWEAVE_CORE_H")
        .with_pragma_once(true)
        .with_autogen_warning("/* Generated by cbindgen. Do not edit by hand. */")
        .generate()
        .expect("cbindgen failed");

    // Write into OUT_DIR for local cargo builds.
    builder.write_to_file(out_dir.join("cmnweave_core.h"));

    // Also write into pkg/agent/grpc/auto/ so the Go cgo bridge can find
    // the header without requiring a full `cargo build` in the CI pipeline.
    // The `make core` target depends on this path.
    let auto_dir = PathBuf::from(&crate_dir)
        .parent()           // pkg/agent/
        .map(|p| p.join("grpc/auto"))
        .expect("could not resolve grpc/auto directory");
    if auto_dir.is_dir() {
        builder.write_to_file(auto_dir.join("cmnweave_core.h"));
    } else {
        eprintln!("cargo:warning=grpc/auto not found at {:?}; skipping header copy", auto_dir);
    }
}

